server:
  port: 8081

spring:
  application:
    name: auth-service

  datasource:
    url: jdbc:mysql://localhost:3306/authdb?createDatabaseIfNotExist=true
    username: root
    password: kilysm
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

springdoc:
  api-docs:
    path: /v3/api-docs        # JSON docs endpoint
  swagger-ui:
    path: /swagger-ui.html   # UI endpoint
    operationsSorter: method
    tagsSorter: alpha
    #persist-authorization: true

jwt:
  secret: 3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b
  expiration: 86400000



eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    lease-renewal-interval-in-seconds: 10
    prefer-ip-address: true
    ip-address: 127.0.0.1
  
management:
  endpoints:
    web:
      exposure:
        include: health, info